let productos = [
    {
        id: 1,
        nombre: 'Trombón Yamaha YSL-154',
        descripcion: 'Trombon Tenor profesional de vara. Ofrece un sonido brillante y cálido, con una vara suave y precisa para músicos de todos los niveles. Su campana de tamaño medio proporciona una proyección óptima. ¡Ideal para mejorar tu música en cualquier entorno!',
        precio: 447912,
        imagen: 'img/trombon_yamaha.png',
        categoria: 'Trombones',
    },
    {
        id: 2,
        nombre: 'Trombón B&S Stolzing BSMS14',
        descripcion: 'Una obra maestra de latón amarillo que ofrece un sonido resonante y claro. Su diseño ergonómico y deslizamiento suave lo convierten en la elección ideal para músicos experimentados. ¡Destaca en cada actuación con este trombón de alta gama! Trombón profesional. Calibre: 11,66mm/0.459″. Campana: 122mm/4,782',
        precio: 186297,
        imagen: 'img/trombon_BS.jpg', 
        categoria: 'Trombones',
    },
    {
        id: 3,
        nombre: 'Trompeta GALA WINDS PTR1100',
        descripcion: 'Con su diseño excepcional y calidad impecable, ofrece un sonido claro y brillante. Su construcción con materiales de alta calidad y precisión en la vara y pistones garantizan una respuesta y afinación óptimas. Ya sea en el escenario, estudio o aula, esta trompeta elevará tu interpretación a nuevos niveles de excelencia.',
        precio: 79791,
        imagen: 'img/trompeta_gala.jpg',
        categoria: 'Trompetas',
    },
    {
        id: 4,
        nombre: 'Trompeta B&S BS3137',
        descripcion: 'Su campana de latón de alta calidad proporciona una resonancia rica y cálida, mientras que su diseño de vara inversa ofrece una respuesta rápida y precisa en todas las notas. Los pistones de acero inoxidable permiten un deslizamiento suave y una afinación precisa, lo que facilita el control del músico sobre su interpretación.',
        precio: 186297,
        imagen: 'img/trompeta_BS.jpg',
        categoria: 'Trompetas',
    },
    {
        id: 5,
        nombre: 'Flauta STAGG WSFL251S',
        descripcion: 'Opción excelente para estudiantes y músicos principiantes. Combina una construcción de calidad con un diseño atractivo y un sonido claro. Construida en plata niquelada, lo que la hace duradera y resistente al desgaste diario. Su mecanismo de llaves es fácil de manejar, lo que permite a los principiantes aprender y tocar cómodamente.',
        precio: 108724,
        imagen: 'img/flauta_stagg.jpg',
        categoria: 'Flautas',
    },
    {
        id: 6,
        nombre: 'Flauta Clef Premium Do',
        descripcion: 'Fabricada con materiales de la más alta calidad, su cuerpo plateado niquelado resalta su belleza y durabilidad. Los mecanismos de llaves precisos y suaves permiten una ejecución cómoda y fluida, mientras que su diseño ergonómico se adapta a tus manos de manera natural, asegurando una experiencia de interpretación sin esfuerzo.',
        precio: 110501,
        imagen: 'img/flauta_clef.jpg',
        categoria: 'Flautas',
    },
];
